var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/projects/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j4tsa_._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0gvrc34.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ge6~7f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y3mp43._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_0v3-fr~._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_projects_page_actions_08dhj-~.js")
R.m(96720)
module.exports=R.m(96720).exports
